/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import aplicacion.Principal;
import basededatos.Conexion;
import com.mysql.jdbc.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RellenarTrabajador = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        GuardarTrabajador = new javax.swing.JButton();
        RellenarSocio = new javax.swing.JFrame();
        txtNombre1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtDireccion1 = new javax.swing.JTextField();
        GuardarSocio = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtClave1 = new javax.swing.JTextField();
        RellenarAceituna = new javax.swing.JFrame();
        txtNombre2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtClave2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        GuardarAceituna = new javax.swing.JButton();
        RellenarCampanya = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        txtFechaINI = new javax.swing.JTextField();
        txtFechaFIN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        GuardarCampanya = new javax.swing.JButton();
        RellenarAceite = new javax.swing.JFrame();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtClave3 = new javax.swing.JTextField();
        txtLitros = new javax.swing.JTextField();
        txtPrecioLitro = new javax.swing.JTextField();
        txtAno1 = new javax.swing.JTextField();
        GuardarAceite = new javax.swing.JButton();
        RellenarRecoleccion = new javax.swing.JFrame();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtAñoRe = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtCodSocio = new javax.swing.JTextField();
        txtKilos = new javax.swing.JTextField();
        txtCodAceituna = new javax.swing.JTextField();
        txtPrecioK = new javax.swing.JTextField();
        txtFechaEntrega = new javax.swing.JTextField();
        GuardarRecoleccion = new javax.swing.JButton();
        InsertarCampanya = new javax.swing.JButton();
        InsertarAceite = new javax.swing.JButton();
        InsertarRecoleccion = new javax.swing.JButton();
        InsertarSocio = new javax.swing.JButton();
        InsertarAceituna = new javax.swing.JButton();
        InsertarTrabajador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        RellenarTrabajador.setMinimumSize(new java.awt.Dimension(350, 450));
        RellenarTrabajador.setPreferredSize(new java.awt.Dimension(350, 450));

        jLabel2.setText("Codigo");

        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Direccion");

        jLabel6.setText("Email");

        jLabel7.setText("Telefono");

        jLabel8.setText("Sueldo");

        jLabel9.setText("Cargo");

        jLabel10.setText("FORMULARIO TRABAJADOR:");

        GuardarTrabajador.setText("Guardar");
        GuardarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarTrabajadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RellenarTrabajadorLayout = new javax.swing.GroupLayout(RellenarTrabajador.getContentPane());
        RellenarTrabajador.getContentPane().setLayout(RellenarTrabajadorLayout);
        RellenarTrabajadorLayout.setHorizontalGroup(
            RellenarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RellenarTrabajadorLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(RellenarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addGroup(RellenarTrabajadorLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RellenarTrabajadorLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RellenarTrabajadorLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(48, 48, 48)
                        .addComponent(txtEmail))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RellenarTrabajadorLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(txtDireccion))
                    .addGroup(RellenarTrabajadorLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(35, 35, 35)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RellenarTrabajadorLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addComponent(txtTelefono))
                    .addGroup(RellenarTrabajadorLayout.createSequentialGroup()
                        .addGroup(RellenarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(40, 40, 40)
                        .addGroup(RellenarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSueldo)
                            .addComponent(txtCargo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RellenarTrabajadorLayout.createSequentialGroup()
                        .addComponent(GuardarTrabajador)
                        .addGap(64, 64, 64)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        RellenarTrabajadorLayout.setVerticalGroup(
            RellenarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RellenarTrabajadorLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(RellenarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RellenarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RellenarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RellenarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RellenarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RellenarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RellenarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RellenarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(GuardarTrabajador)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        RellenarSocio.setMinimumSize(new java.awt.Dimension(350, 300));
        RellenarSocio.setPreferredSize(new java.awt.Dimension(350, 300));

        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Nombre");

        jLabel14.setText("Apellido");

        jLabel15.setText("FORMULARIO SOCIO:");

        GuardarSocio.setText("Guardar");
        GuardarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarSocioActionPerformed(evt);
            }
        });

        jLabel16.setText("Direccion");

        jLabel17.setText("Email");

        jLabel18.setText("Codigo");

        jLabel19.setText("Telefono");

        txtClave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClave1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RellenarSocioLayout = new javax.swing.GroupLayout(RellenarSocio.getContentPane());
        RellenarSocio.getContentPane().setLayout(RellenarSocioLayout);
        RellenarSocioLayout.setHorizontalGroup(
            RellenarSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RellenarSocioLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(RellenarSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addGroup(RellenarSocioLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(39, 39, 39)
                        .addComponent(txtClave1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RellenarSocioLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(35, 35, 35)
                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RellenarSocioLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(48, 48, 48)
                        .addComponent(txtEmail1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RellenarSocioLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(29, 29, 29)
                        .addComponent(txtDireccion1))
                    .addGroup(RellenarSocioLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(35, 35, 35)
                        .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RellenarSocioLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(30, 30, 30)
                        .addComponent(txtTelefono1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RellenarSocioLayout.createSequentialGroup()
                        .addComponent(GuardarSocio)
                        .addGap(64, 64, 64)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        RellenarSocioLayout.setVerticalGroup(
            RellenarSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RellenarSocioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(RellenarSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtClave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RellenarSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RellenarSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RellenarSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RellenarSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RellenarSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(GuardarSocio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RellenarAceituna.setMinimumSize(new java.awt.Dimension(400, 220));
        RellenarAceituna.setPreferredSize(new java.awt.Dimension(400, 220));

        txtNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Nombre");

        jLabel20.setText("Codigo");

        txtClave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClave2ActionPerformed(evt);
            }
        });

        jLabel21.setText("FORMULARIO ACEITUNA:");

        GuardarAceituna.setText("Guardar");
        GuardarAceituna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarAceitunaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RellenarAceitunaLayout = new javax.swing.GroupLayout(RellenarAceituna.getContentPane());
        RellenarAceituna.getContentPane().setLayout(RellenarAceitunaLayout);
        RellenarAceitunaLayout.setHorizontalGroup(
            RellenarAceitunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RellenarAceitunaLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(GuardarAceituna)
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(RellenarAceitunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RellenarAceitunaLayout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addGroup(RellenarAceitunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel21)
                        .addGroup(RellenarAceitunaLayout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(39, 39, 39)
                            .addComponent(txtClave2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(RellenarAceitunaLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(35, 35, 35)
                            .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(77, Short.MAX_VALUE)))
        );
        RellenarAceitunaLayout.setVerticalGroup(
            RellenarAceitunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RellenarAceitunaLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(GuardarAceituna)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RellenarAceitunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RellenarAceitunaLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel21)
                    .addGap(18, 18, 18)
                    .addGroup(RellenarAceitunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(txtClave2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(RellenarAceitunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(54, Short.MAX_VALUE)))
        );

        RellenarCampanya.setMinimumSize(new java.awt.Dimension(420, 360));
        RellenarCampanya.setPreferredSize(new java.awt.Dimension(420, 360));

        jLabel11.setText("RELLENAR CAMPAÑA:");

        jLabel22.setText("Año");

        jLabel23.setText("Fecha Inicio");

        jLabel24.setText("Fecha Final");

        jLabel25.setText("Observaciones:");

        txtAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoActionPerformed(evt);
            }
        });

        txtFechaINI.setText("YYYY-MM-DD");

        txtFechaFIN.setText("YYYY-MM-DD");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        GuardarCampanya.setText("Guardar");
        GuardarCampanya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCampanyaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RellenarCampanyaLayout = new javax.swing.GroupLayout(RellenarCampanya.getContentPane());
        RellenarCampanya.getContentPane().setLayout(RellenarCampanyaLayout);
        RellenarCampanyaLayout.setHorizontalGroup(
            RellenarCampanyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RellenarCampanyaLayout.createSequentialGroup()
                .addGroup(RellenarCampanyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RellenarCampanyaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(RellenarCampanyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25)
                            .addComponent(jLabel11)
                            .addGroup(RellenarCampanyaLayout.createSequentialGroup()
                                .addGroup(RellenarCampanyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel22))
                                .addGap(18, 18, 18)
                                .addGroup(RellenarCampanyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAno)
                                    .addComponent(txtFechaINI, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addGroup(RellenarCampanyaLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(21, 21, 21)
                                .addComponent(txtFechaFIN))))
                    .addGroup(RellenarCampanyaLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(GuardarCampanya)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        RellenarCampanyaLayout.setVerticalGroup(
            RellenarCampanyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RellenarCampanyaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addGroup(RellenarCampanyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RellenarCampanyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtFechaINI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(RellenarCampanyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtFechaFIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(GuardarCampanya)
                .addContainerGap())
        );

        RellenarAceite.setMinimumSize(new java.awt.Dimension(410, 270));
        RellenarAceite.setPreferredSize(new java.awt.Dimension(410, 270));

        jLabel26.setText("RELLENAR ACEITE:");

        jLabel27.setText("Codigo");

        jLabel28.setText("Litros ");

        jLabel29.setText("Precio Litro");

        jLabel30.setText("Año");

        GuardarAceite.setText("Guardar");
        GuardarAceite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarAceiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RellenarAceiteLayout = new javax.swing.GroupLayout(RellenarAceite.getContentPane());
        RellenarAceite.getContentPane().setLayout(RellenarAceiteLayout);
        RellenarAceiteLayout.setHorizontalGroup(
            RellenarAceiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RellenarAceiteLayout.createSequentialGroup()
                .addGroup(RellenarAceiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RellenarAceiteLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(RellenarAceiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26)
                            .addGroup(RellenarAceiteLayout.createSequentialGroup()
                                .addGroup(RellenarAceiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(RellenarAceiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecioLitro)
                                    .addComponent(txtAno1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)))
                            .addGroup(RellenarAceiteLayout.createSequentialGroup()
                                .addGroup(RellenarAceiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel27))
                                .addGap(30, 30, 30)
                                .addGroup(RellenarAceiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtClave3)
                                    .addComponent(txtLitros, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)))))
                    .addGroup(RellenarAceiteLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(GuardarAceite)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        RellenarAceiteLayout.setVerticalGroup(
            RellenarAceiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RellenarAceiteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(RellenarAceiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtClave3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RellenarAceiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtLitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RellenarAceiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtPrecioLitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RellenarAceiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtAno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(GuardarAceite)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RellenarRecoleccion.setMinimumSize(new java.awt.Dimension(400, 370));
        RellenarRecoleccion.setPreferredSize(new java.awt.Dimension(400, 370));

        jLabel31.setText("FORMULARIO RECOLECCION:");

        jLabel32.setText("Codigo");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel33.setText("Año");

        jLabel34.setText("Codigo Socio");

        jLabel35.setText("Codigo Aceituna");

        jLabel36.setText("Kilos");

        jLabel37.setText("Precio Kilo");

        jLabel38.setText("Fecha Entrega");

        txtCodSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodSocioActionPerformed(evt);
            }
        });

        txtFechaEntrega.setText("YYYY-MM-DD");

        GuardarRecoleccion.setText("Guardar");
        GuardarRecoleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarRecoleccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RellenarRecoleccionLayout = new javax.swing.GroupLayout(RellenarRecoleccion.getContentPane());
        RellenarRecoleccion.getContentPane().setLayout(RellenarRecoleccionLayout);
        RellenarRecoleccionLayout.setHorizontalGroup(
            RellenarRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RellenarRecoleccionLayout.createSequentialGroup()
                .addGroup(RellenarRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RellenarRecoleccionLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(RellenarRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(RellenarRecoleccionLayout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addGap(18, 18, 18)
                                .addComponent(txtFechaEntrega))
                            .addGroup(RellenarRecoleccionLayout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addGap(40, 40, 40)
                                .addComponent(txtPrecioK))
                            .addGroup(RellenarRecoleccionLayout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodAceituna))
                            .addComponent(jLabel31)
                            .addGroup(RellenarRecoleccionLayout.createSequentialGroup()
                                .addGroup(RellenarRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33))
                                .addGap(54, 54, 54)
                                .addGroup(RellenarRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtAñoRe, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(RellenarRecoleccionLayout.createSequentialGroup()
                                .addGroup(RellenarRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel36))
                                .addGroup(RellenarRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RellenarRecoleccionLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(txtCodSocio))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RellenarRecoleccionLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtKilos, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(RellenarRecoleccionLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(GuardarRecoleccion)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        RellenarRecoleccionLayout.setVerticalGroup(
            RellenarRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RellenarRecoleccionLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addGroup(RellenarRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RellenarRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtAñoRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RellenarRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtCodSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RellenarRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtCodAceituna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(RellenarRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txtKilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RellenarRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txtPrecioK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RellenarRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txtFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(GuardarRecoleccion)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InsertarCampanya.setText("Campanya");
        InsertarCampanya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarCampanyaActionPerformed(evt);
            }
        });

        InsertarAceite.setText("Aceite");
        InsertarAceite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarAceiteActionPerformed(evt);
            }
        });

        InsertarRecoleccion.setText("Recoleccion");
        InsertarRecoleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarRecoleccionActionPerformed(evt);
            }
        });

        InsertarSocio.setText("Socios");
        InsertarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarSocioActionPerformed(evt);
            }
        });

        InsertarAceituna.setText("Tipos_Aceituana");
        InsertarAceituna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarAceitunaActionPerformed(evt);
            }
        });

        InsertarTrabajador.setText("Trabajadores");
        InsertarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarTrabajadorActionPerformed(evt);
            }
        });

        jLabel1.setText("Elija el elemento que quiere introducir:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(InsertarRecoleccion)
                    .addComponent(InsertarAceite)
                    .addComponent(InsertarTrabajador)
                    .addComponent(InsertarAceituna)
                    .addComponent(InsertarSocio)
                    .addComponent(InsertarCampanya))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(InsertarTrabajador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertarSocio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertarAceituna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertarCampanya)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertarAceite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InsertarRecoleccion)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarTrabajadorActionPerformed
        RellenarTrabajador.setVisible(true);
    }//GEN-LAST:event_InsertarTrabajadorActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void GuardarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarTrabajadorActionPerformed
        Connection con = (Connection) Principal.miConexion.getConexion();
        PreparedStatement ps;
        try{
            
            ps = con.prepareStatement("INSERT INTO TRABAJADORES (codigoTrabajador, nombreTrabajador, apellidosTrabajador, "
                    + "direccionTrabajador, emailTrabajador, telefonoTrabajador,  sueldoTrabajador, cargoTrabajador) VALUES(?,?,?,?,?,?,?,?) ");
            ps.setInt(1, Integer.parseInt(txtClave.getText()));
            ps.setString(2, txtNombre.getText());
            ps.setString(3, txtApellido.getText());
            ps.setString(4, txtDireccion.getText());
            ps.setString(5, txtEmail.getText());
            ps.setInt(6, Integer.parseInt(txtTelefono.getText()));
            ps.setDouble(7, Double.parseDouble(txtSueldo.getText()));
            ps.setString(8, txtCargo.getText());
            
            int res = ps.executeUpdate();
            
            if(res > 0){
                JOptionPane.showMessageDialog(null, "Trabajador Guardado");
                //limpiarCajas();
            } else {
                 JOptionPane.showMessageDialog(null, "Error al Guardar trabajador");
                //limpiarCajas();
            }
            
            
            
        } catch(Exception e){
            System.err.println(e);
        }
        
    }//GEN-LAST:event_GuardarTrabajadorActionPerformed

    private void InsertarAceiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarAceiteActionPerformed
        RellenarAceite.setVisible(true);
    }//GEN-LAST:event_InsertarAceiteActionPerformed

    private void InsertarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarSocioActionPerformed
        RellenarSocio.setVisible(true);
    }//GEN-LAST:event_InsertarSocioActionPerformed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void GuardarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarSocioActionPerformed
        Connection con = (Connection) Principal.miConexion.getConexion();
        PreparedStatement ps;
        try{
            
            ps = con.prepareStatement("INSERT INTO SOCIOS (codigoSocio, nombreSocio, apellidosSocio, "
                    + "direccionSocio, emailSocio, telefonoSocio) VALUES(?,?,?,?,?,?) ");
            ps.setInt(1, Integer.parseInt(txtClave1.getText()));
            ps.setString(2, txtNombre1.getText());
            ps.setString(3, txtApellido1.getText());
            ps.setString(4, txtDireccion1.getText());
            ps.setString(5, txtEmail1.getText());
            ps.setString(6, txtTelefono1.getText());
            
            int res = ps.executeUpdate();
            
            if(res > 0){
                JOptionPane.showMessageDialog(null, "Socio Guardado");
                //limpiarCajas();
            } else {
                 JOptionPane.showMessageDialog(null, "Error al Guardar socio");
                //limpiarCajas();
            }
            
            
            
        } catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_GuardarSocioActionPerformed

    private void txtClave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClave1ActionPerformed

    private void InsertarAceitunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarAceitunaActionPerformed
        RellenarAceituna.setVisible(true);
    }//GEN-LAST:event_InsertarAceitunaActionPerformed

    private void txtNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2ActionPerformed

    private void txtClave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClave2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClave2ActionPerformed

    private void GuardarAceitunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarAceitunaActionPerformed
        Connection con = (Connection) Principal.miConexion.getConexion();
        PreparedStatement ps;
        try{
            
            ps = con.prepareStatement("INSERT INTO TIPOS_ACEITUNA (codigoAceituna, nombreAceituna) VALUES(?,?) ");
            ps.setInt(1, Integer.parseInt(txtClave2.getText()));
            ps.setString(2, txtNombre2.getText());
            
            int res = ps.executeUpdate();
            
            if(res > 0){
                JOptionPane.showMessageDialog(null, "Aceituna Guardada");
                //limpiarCajas();
            } else {
                 JOptionPane.showMessageDialog(null, "Error al Guardar aceituna");
                //limpiarCajas();
            }
            
            
            
        } catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_GuardarAceitunaActionPerformed

    private void InsertarCampanyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarCampanyaActionPerformed
        RellenarCampanya.setVisible(true);
    }//GEN-LAST:event_InsertarCampanyaActionPerformed

    private void txtAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoActionPerformed

    private void GuardarCampanyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCampanyaActionPerformed
        Connection con = (Connection) Principal.miConexion.getConexion();
        PreparedStatement ps;
        try{
            
            ps = con.prepareStatement("INSERT INTO CAMPANYA (anyo, fechaInicio, fechaFinal, observaciones) VALUES(?,?,?,?) ");
            ps.setString(1, txtAno.getText());
            ps.setDate(2, Date.valueOf(txtFechaINI.getText()));
            ps.setDate(3, Date.valueOf(txtFechaFIN.getText()));
            ps.setString(4, txtObservaciones.getText());
            
            int res = ps.executeUpdate();
            
            if(res > 0){
                JOptionPane.showMessageDialog(null, "Camapaña Guardada");
                //limpiarCajas();
            } else {
                 JOptionPane.showMessageDialog(null, "Error al Guardar campaña");
                //limpiarCajas();
            }
            
            
            
        } catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_GuardarCampanyaActionPerformed

    private void GuardarAceiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarAceiteActionPerformed
        Connection con = (Connection) Principal.miConexion.getConexion();
        PreparedStatement ps;
        try{
            
            ps = con.prepareStatement("INSERT INTO ACEITE (codigoProduccion, litros, precioLitro, anyo) VALUES(?,?,?,?) ");
            ps.setInt(1, Integer.parseInt(txtClave3.getText()));
            ps.setInt(2, Integer.parseInt(txtLitros.getText()));
            ps.setFloat(3, Float.parseFloat(txtPrecioLitro.getText()));
            ps.setString(4, txtAno1.getText());
            
            
            int res = ps.executeUpdate();
            
            if(res > 0){
                JOptionPane.showMessageDialog(null, "Aceite Guardado");
                //limpiarCajas();
            } else {
                 JOptionPane.showMessageDialog(null, "Error al Guardar aceite");
                //limpiarCajas();
            }
            
            
            
        } catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_GuardarAceiteActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void InsertarRecoleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarRecoleccionActionPerformed
        RellenarRecoleccion.setVisible(true);
    }//GEN-LAST:event_InsertarRecoleccionActionPerformed

    private void GuardarRecoleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarRecoleccionActionPerformed
        Connection con = (Connection) Principal.miConexion.getConexion();
        PreparedStatement ps;
        try{
            
            ps = con.prepareStatement("INSERT INTO RECOLECCION (codigoRecoleccion, anyo, codigoSocio, codigoAceituna, kilos, "
                    + "precioKilo, fecha) VALUES(?,?,?,?,?,?,?) ");
            ps.setInt(1, Integer.parseInt(txtCodigo.getText()));
            ps.setString(2, txtAñoRe.getText());
            ps.setInt(3, Integer.parseInt(txtCodSocio.getText()));
            ps.setInt(4, Integer.parseInt(txtCodAceituna.getText()));
            ps.setInt(5, Integer.parseInt(txtKilos.getText()));
            ps.setFloat(6, Float.parseFloat(txtPrecioK.getText()));
            ps.setDate(7, Date.valueOf(txtFechaEntrega.getText()));
            
            
            int res = ps.executeUpdate();
            
            if(res > 0){
                JOptionPane.showMessageDialog(null, "Recoleccion Guardada");
                //limpiarCajas();
            } else {
                 JOptionPane.showMessageDialog(null, "Error al Guardar Recoleccion");
                //limpiarCajas();
            }
            
            
            
        } catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_GuardarRecoleccionActionPerformed

    private void txtCodSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodSocioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarAceite;
    private javax.swing.JButton GuardarAceituna;
    private javax.swing.JButton GuardarCampanya;
    private javax.swing.JButton GuardarRecoleccion;
    private javax.swing.JButton GuardarSocio;
    private javax.swing.JButton GuardarTrabajador;
    private javax.swing.JButton InsertarAceite;
    private javax.swing.JButton InsertarAceituna;
    private javax.swing.JButton InsertarCampanya;
    private javax.swing.JButton InsertarRecoleccion;
    private javax.swing.JButton InsertarSocio;
    private javax.swing.JButton InsertarTrabajador;
    private javax.swing.JFrame RellenarAceite;
    private javax.swing.JFrame RellenarAceituna;
    private javax.swing.JFrame RellenarCampanya;
    private javax.swing.JFrame RellenarRecoleccion;
    private javax.swing.JFrame RellenarSocio;
    private javax.swing.JFrame RellenarTrabajador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtAno1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtAñoRe;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtClave1;
    private javax.swing.JTextField txtClave2;
    private javax.swing.JTextField txtClave3;
    private javax.swing.JTextField txtCodAceituna;
    private javax.swing.JTextField txtCodSocio;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccion1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtFechaEntrega;
    private javax.swing.JTextField txtFechaFIN;
    private javax.swing.JTextField txtFechaINI;
    private javax.swing.JTextField txtKilos;
    private javax.swing.JTextField txtLitros;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtPrecioK;
    private javax.swing.JTextField txtPrecioLitro;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono1;
    // End of variables declaration//GEN-END:variables
}

